### ISSUE TITLE
Run Cron Job without Crontab

### ISSUE THREAD

**Issue by thimma11** [Tivix/django-cron#131]
Hi, kinda stupid question, but is it possible to run cron jobs without creating a cronjob in linux (crontab -e). Otherwise, why would you specify the schedule in the cron class, altough it's already specified in the cronjob itself?

**Comment by maxim-kht** [comment]
Hi @thimma11, no, it is not possible - in order for django-cron to work, it needs cronjob to execute it. 
Specifying the schedule in the cron classes allows you to put all the logic regarding scheduling your Django tasks into a module inside Django. Otherwise you would need to manually create cron command and Django management command for each task you want to execute separately.
