### ISSUE TITLE
Question about calling runcrons while a previous job is happening

### ISSUE THREAD

**Issue by DanielStevenLewis** [Tivix/django-cron#67]
If manage.py runcrons is called while a django-cron do function hasn't yet finished running, and that django-cron do function isn't scheduled to run again yet at that point in time, will there be a problem? I'm asking because I'm wondering whether some issues I'm experiencing might be due to having scheduled the (crontab -e) cron job to run too frequently.

**Comment by craiglabenz** [comment]
`django-cron` uses your configured cache backend to store which jobs are currently in-flight. Unless you designate a job as being able to run in parallel, `django-cron` will not re-invoke it while an earlier version is still working.

**Comment by chachra** [comment]
@craiglabenz thanks for answering. @DanielStevenLewis as Craig mentioned its all configurable. If you allow parallel runs and crontab executes these quicker than necessary (say via bash file that goes in a loop) or every second and the cron python execution is slow because of whatever reason, then you could easily end up with a ton of processes which is a potential problem. Hence by default parallel runs for the same cron (code) don't work.
