### ISSUE TITLE
Scheduling with run_at_times and crontab entry

### ISSUE THREAD

**Issue by varunasingh** [Tivix/django-cron#98]
Great library and we are using it. Im actually a bit confused on this topic. Say I want a job to run at 4:20 pm every day and I have added run_at_times to ['16:20'] . 

I know the library works by adding runcrons command to crontab but I'm not aware the best way to add the entry to crontab. 

If I add a crontab entry every 5 minutes (*/5 * * * *), would it reach a point where crontab would run it and skip the 4:20pm mark and not run it at all?  If I edit crontab with  (* * * * *) how am I sure that cron will run it exacrtly at 4:20pm such that django-cron can run too. 

Thanks, hope that made sense.

**Comment by craiglabenz** [comment]
@varunasingh I haven't used this library in a while, but IIRC, you basically want your crontab job to run as frequently as possible. The first time `run_crons` executes on or after 4:20, it will start your specific job and mark that it did so (so that no future crontab invocations repeat the work).

Thus, if you set your crontab to invoke the `run_crons` command every 5 seconds, your specific 4:20 job could be executed as late as 4:20:04.999, or something of the sort. Obviously setting it to every second, or other second, will tighten that window.

Hope that helps!

**Comment by varunasingh** [comment]
Great, that does explain it. The only real solution to RUN_AT_TIMES is have cron run every few seconds or  so that the time specified in django-cron gets picked up. Not sure if its an elegant way but it is a way. Thanks for the quick and clear response.

**Comment by craiglabenz** [comment]
@varunasingh If your use case is such that a few second noise is too great, you could also look at [celery's periodic tasks](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html).
